# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBGGxoHUw2btLK3XSJ8Qn_AZXmD8udDi
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score, mean_absolute_error

df = pd.read_csv('supply_chain_data.csv')
print(f"✓ Veri yüklendi: {df.shape[0]} ürün, {df.shape[1]} özellik")
df.head()

# Görselleştirme: Genel Bakış
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle('Tedarik Zinciri — Genel Bakış', fontsize=14, fontweight='bold')

colors = ['#2E75B6', '#E24B4A', '#1F9E75', '#F2A623', '#7030A0']

# 1. Ürün tipi dağılımı
ax = axes[0,0]
pt_counts = df['Product type'].value_counts()
ax.pie(pt_counts.values, labels=pt_counts.index, autopct='%1.1f%%',
       colors=colors[:len(pt_counts)], startangle=90)
ax.set_title('Ürün Tipi Dağılımı', fontweight='bold')

# 2. Tedarikçi başına gelir
ax = axes[0,1]
supplier_rev = df.groupby('Supplier name')['Revenue generated'].sum().sort_values(ascending=True)
bars = ax.barh(supplier_rev.index, supplier_rev.values/1000, color=colors[:len(supplier_rev)])
ax.set_xlabel('Gelir (K)')
ax.set_title('Tedarikçi Başına Gelir', fontweight='bold')

# 3. Taşıma modu vs maliyet
ax = axes[0,2]
trans_cost = df.groupby('Transportation modes')['Shipping costs'].mean().sort_values(ascending=False)
ax.bar(trans_cost.index, trans_cost.values, color=colors[:len(trans_cost)], alpha=0.85)
ax.set_title('Taşıma Modu — Ort. Kargo Maliyeti', fontweight='bold')
ax.set_ylabel('Ortalama Maliyet')
ax.tick_params(axis='x', rotation=15)

# 4. Stok seviyeleri
ax = axes[1,0]
ax.hist(df['Stock levels'], bins=20, color='#2E75B6', alpha=0.7, edgecolor='white')
ax.axvline(df['Stock levels'].mean(), color='red', linestyle='--',
           label=f"Ort: {df['Stock levels'].mean():.0f}")
ax.set_title('Stok Seviyesi Dağılımı', fontweight='bold')
ax.legend()

# 5. Lead time vs sipariş miktarı
ax = axes[1,1]
scatter = ax.scatter(df['Lead times'], df['Order quantities'],
                     c=df['Costs'], cmap='RdYlGn_r', alpha=0.7, s=60)
plt.colorbar(scatter, ax=ax, label='Maliyet')
ax.set_xlabel('Temin Süresi (gün)')
ax.set_ylabel('Sipariş Miktarı')
ax.set_title('Temin Süresi vs Sipariş Miktarı', fontweight='bold')

# 6. Hata oranı
ax = axes[1,2]
for i, pt in enumerate(df['Product type'].unique()):
    sub = df[df['Product type']==pt]
    ax.hist(sub['Defect rates'], bins=15, alpha=0.6, label=pt, color=colors[i])
ax.set_title('Hata Oranı — Ürün Tipine Göre', fontweight='bold')
ax.legend()

plt.tight_layout()
plt.show()

# Bullwhip Etkisi Simülasyonu
np.random.seed(42)
T = 52  # 52 hafta

mean_demand = df['Number of products sold'].mean() / 52
std_demand  = df['Number of products sold'].std()  / 52
mean_lt     = df['Lead times'].mean()

print(f"Gerçek veriden parametreler:")
print(f"  Haftalık ortalama talep : {mean_demand:.1f}")
print(f"  Talep std sapması       : {std_demand:.1f}")
print(f"  Ortalama temin süresi   : {mean_lt:.1f} gün")

# Tüketici talebi
trend    = np.linspace(0, 10, T)
seasonal = 15 * np.sin(2 * np.pi * np.arange(T) / 26)
noise    = np.random.normal(0, std_demand*0.3, T)
consumer_demand = np.maximum(0, mean_demand + trend + seasonal + noise)

def simulate_echelon(upstream_orders, lt, alpha=0.3, safety_factor=1.5):
    orders    = np.zeros(T)
    inventory = np.zeros(T)
    inventory[0] = mean_demand * lt * safety_factor
    for t in range(1, T):
        if t == 1:
            demand_forecast = upstream_orders[t-1]
        else:
            demand_forecast = alpha * upstream_orders[t-1] + (1-alpha) * np.mean(upstream_orders[max(0,t-5):t])
        target_inv  = demand_forecast * lt * safety_factor
        orders[t]   = max(0, demand_forecast + target_inv - inventory[t-1])
        received    = orders[max(0, t-int(lt))] if t > lt else 0
        inventory[t]= max(0, inventory[t-1] - upstream_orders[t-1] + received)
    return orders, inventory

retailer_orders,     retailer_inv     = simulate_echelon(consumer_demand,    1.0)
wholesaler_orders,   wholesaler_inv   = simulate_echelon(retailer_orders,    2.0)
manufacturer_orders, manufacturer_inv = simulate_echelon(wholesaler_orders,  3.0)
supplier_orders,     supplier_inv     = simulate_echelon(manufacturer_orders, 4.0)

def bullwhip_ratio(orders, demand):
    return np.var(orders) / np.var(demand) if np.var(demand) > 0 else 1

bwe_retailer     = bullwhip_ratio(retailer_orders,     consumer_demand)
bwe_wholesaler   = bullwhip_ratio(wholesaler_orders,   consumer_demand)
bwe_manufacturer = bullwhip_ratio(manufacturer_orders, consumer_demand)
bwe_supplier     = bullwhip_ratio(supplier_orders,     consumer_demand)

print(f"\nBullwhip Etkisi Oranları:")
print(f"  Perakendeci : {bwe_retailer:.2f}x")
print(f"  Toptancı    : {bwe_wholesaler:.2f}x")
print(f"  Üretici     : {bwe_manufacturer:.2f}x")
print(f"  Tedarikçi   : {bwe_supplier:.2f}x")

# Bullwhip Görselleştirme
fig, axes = plt.subplots(3, 1, figsize=(14, 12))
fig.suptitle('Bullwhip Etkisi — 4 Kademeli Tedarik Zinciri Simülasyonu',
             fontsize=13, fontweight='bold')

weeks = np.arange(T)
echelons = [
    ('Tüketici Talebi',  consumer_demand,      '#2E75B6'),
    ('Perakendeci',      retailer_orders,       '#1F9E75'),
    ('Toptancı',         wholesaler_orders,     '#F2A623'),
    ('Üretici',          manufacturer_orders,   '#E24B4A'),
    ('Tedarikçi',        supplier_orders,       '#7030A0'),
]

# Üst: tüm kademeler
ax1 = axes[0]
for name, data, color in echelons:
    ax1.plot(weeks, data, label=name, color=color, linewidth=1.5)
ax1.set_title('Sipariş Miktarları — Tüm Kademeler', fontweight='bold')
ax1.set_ylabel('Sipariş Miktarı')
ax1.legend(fontsize=9)
ax1.grid(alpha=0.3)

# Orta: BWE oranları
ax2 = axes[1]
bwe_vals  = [1, bwe_retailer, bwe_wholesaler, bwe_manufacturer, bwe_supplier]
bwe_names = ['Tüketici', 'Perakendeci', 'Toptancı', 'Üretici', 'Tedarikçi']
bwe_colors= ['#2E75B6','#1F9E75','#F2A623','#E24B4A','#7030A0']
bars = ax2.bar(bwe_names, bwe_vals, color=bwe_colors, alpha=0.85)
ax2.axhline(y=1, color='black', linestyle='--', alpha=0.5, label='BWE=1 (İdeal)')
ax2.set_title('Bullwhip Etkisi Oranı (BWE)', fontweight='bold')
ax2.set_ylabel('BWE Oranı')
ax2.legend()
for bar, val in zip(bars, bwe_vals):
    ax2.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.05,
             f'{val:.2f}x', ha='center', fontsize=10, fontweight='bold')

# Alt: stok seviyeleri
ax3 = axes[2]
for name, inv, color in [
    ('Perakendeci',  retailer_inv,     '#1F9E75'),
    ('Toptancı',     wholesaler_inv,   '#F2A623'),
    ('Üretici',      manufacturer_inv, '#E24B4A'),
]:
    ax3.plot(weeks, inv, label=name, color=color, linewidth=1.5)
ax3.axhline(y=0, color='red', linestyle=':', alpha=0.5, label='Stok Tükenmesi')
ax3.set_title('Stok Seviyeleri', fontweight='bold')
ax3.set_xlabel('Hafta')
ax3.set_ylabel('Stok Miktarı')
ax3.legend(fontsize=9)
ax3.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# Tedarikçi Performans & Maliyet Görselleştirme
# Define missing variables before plotting
suppliers = df['Supplier name'].unique()

supplier_metrics = df.groupby('Supplier name').agg(
    Ort_Revenue=('Revenue generated', 'mean'),
    Ort_Defect_Rate=('Defect rates', 'mean'),
    Ort_Lead_Time=('Lead time', 'mean'),
    Ort_Maliyet=('Manufacturing costs', 'mean'),
    Ort_Uretim_Hacmi=('Production volumes', 'mean')
).reset_index()

# Normalize metrics to calculate performance score (0-100)
# Higher revenue is better, lower defect rate/lead time/cost are better
max_revenue = supplier_metrics['Ort_Revenue'].max()
min_revenue = supplier_metrics['Ort_Revenue'].min()
max_defect = supplier_metrics['Ort_Defect_Rate'].max()
min_defect = supplier_metrics['Ort_Defect_Rate'].min()

epsilon = 1e-6 # To prevent division by zero

supplier_metrics['Norm_Revenue'] = (supplier_metrics['Ort_Revenue'] - min_revenue) / (max_revenue - min_revenue + epsilon)
supplier_metrics['Norm_Defect_Rate_Inv'] = (1 - (supplier_metrics['Ort_Defect_Rate'] - min_defect) / (max_defect - min_defect + epsilon))

# Combine normalized metrics for a 'Performans_Skoru' (e.g., 60% revenue, 40% inverse defect rate)
supplier_metrics['Performans_Skoru'] = (supplier_metrics['Norm_Revenue'] * 0.6 + supplier_metrics['Norm_Defect_Rate_Inv'] * 0.4) * 100
supplier_metrics['Performans_Skoru'] = supplier_metrics['Performans_Skoru'].round(2)

# Prepare supplier_perf DataFrame for plotting
supplier_perf = supplier_metrics.rename(columns={
    'Ort_Lead_Time': 'Ort_Temin_Suresi',
    'Ort_Defect_Rate': 'Ort_Hata_Orani' # Renaming the column here
})
supplier_perf = supplier_perf[['Supplier name', 'Performans_Skoru', 'Ort_Temin_Suresi', 'Ort_Maliyet', 'Ort_Uretim_Hacmi', 'Ort_Hata_Orani']] # Explicitly selecting the renamed column
supplier_perf = supplier_perf.set_index('Supplier name')

# Define colors for suppliers
# Reusing the 'colors' variable defined in a previous cell, which has 5 colors.
# Assuming there are 5 suppliers as per 'supplier_rev' in kernel state.
s_colors = colors[:len(suppliers)]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Tedarikçi Performans & Maliyet Analizi', fontsize=13, fontweight='bold')

# 1. Performans skoru
ax = axes[0,0]
bars = ax.bar(suppliers, supplier_perf['Performans_Skoru'], color=s_colors, alpha=0.85)
ax.set_title('Tedarikçi Performans Skoru', fontweight='bold')
ax.set_ylabel('Skor (0-100)')
ax.set_ylim(0, 100)
for bar, val in zip(bars, supplier_perf['Performans_Skoru']):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,
            f'{val}', ha='center', fontsize=11, fontweight='bold')

# 2. Maliyet vs temin süresi
ax = axes[0,1]
for i, (sup, row) in enumerate(supplier_perf.iterrows()):
    ax.scatter(row['Ort_Temin_Suresi'], row['Ort_Maliyet'],
               s=row['Ort_Uretim_Hacmi']/5, color=s_colors[i], alpha=0.8, zorder=5)
    ax.annotate(sup, (row['Ort_Temin_Suresi'], row['Ort_Maliyet']),
                fontsize=9, ha='center', va='bottom')
ax.set_xlabel('Ortalama Temin Süresi (gün)')
ax.set_ylabel('Ortalama Üretim Maliyeti')
ax.set_title('Temin Süresi vs Maliyet\n(Balon = Üretim hacmi)', fontweight='bold')

# 3. Taşıma modu karşılaştırması
ax = axes[1,0]
trans_analysis = df.groupby('Transportation modes').agg(
    Ort_Kargo=('Shipping costs', 'mean'),
    Ort_Sure =('Shipping times', 'mean'),
).round(2)
x = np.arange(len(trans_analysis))
w = 0.35
ax.bar(x-w/2, trans_analysis['Ort_Kargo'],   w, label='Kargo Maliyeti', color='#E24B4A', alpha=0.85)
ax.bar(x+w/2, trans_analysis['Ort_Sure']*10, w, label='Süre×10 (gün)', color='#2E75B6', alpha=0.85)
ax.set_xticks(x)
ax.set_xticklabels(trans_analysis.index, rotation=15)
ax.set_title('Taşıma Modu — Maliyet & Süre', fontweight='bold')
ax.legend()

# 4. ABC analizi
ax = axes[1,1]
df_abc = df.copy()
df_abc['Revenue_pct'] = df_abc['Revenue generated'] / df_abc['Revenue generated'].sum() * 100
df_abc = df_abc.sort_values('Revenue generated', ascending=False)
df_abc['Cumulative_pct'] = df_abc['Revenue_pct'].cumsum()
df_abc['ABC'] = pd.cut(df_abc['Cumulative_pct'],
                        bins=[0,80,95,100],
                        labels=['A (%80)', 'B (%15)', 'C (%5)'])
abc_counts = df_abc['ABC'].value_counts()
ax.pie(abc_counts.values, labels=abc_counts.index,
       autopct='%1.1f%%', colors=['#1F9E75','#F2A623','#E24B4A'],
       startangle=90, explode=[0.05,0,0])
ax.set_title('ABC Analizi', fontweight='bold')

plt.tight_layout()
plt.show()

# ML Modeli — Maliyet Tahmini
le = LabelEncoder()
df_ml = df.copy()
for col in ['Product type','Supplier name','Location',
            'Transportation modes','Routes','Shipping carriers']:
    df_ml[col+'_enc'] = le.fit_transform(df_ml[col])

df_ml['total_lead_time'] = df_ml['Lead times'] + df_ml['Manufacturing lead time']
df_ml['cost_per_unit']   = df_ml['Costs'] / (df_ml['Order quantities'] + 1)
df_ml['stock_turnover']  = df_ml['Number of products sold'] / (df_ml['Stock levels'] + 1)

features = ['Price','Stock levels','Lead times','Order quantities',
            'Shipping costs','Lead time','Production volumes',
            'Manufacturing lead time','Manufacturing costs','Defect rates',
            'Product type_enc','Supplier name_enc','Transportation modes_enc',
            'total_lead_time','cost_per_unit','stock_turnover']

X = df_ml[features]
y = df_ml['Costs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models_ml = {
    'Linear Regression': LinearRegression(),
    'Random Forest':     RandomForestRegressor(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=100, random_state=42),
}

print(f"{'Model':<25} {'R²':>8} {'MAE':>10}")
print("-"*45)
results_ml = {}
for name, model in models_ml.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2  = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    results_ml[name] = {'model':model,'y_pred':y_pred,'r2':r2,'mae':mae}
    print(f"{name:<25} {r2:>8.3f} {mae:>10.1f}")

rf = results_ml['Random Forest']['model']
feat_imp = pd.Series(rf.feature_importances_, index=features).sort_values(ascending=False).head(8)

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('Maliyet Tahmin Modeli — ML Sonuçları', fontsize=13, fontweight='bold')

ax = axes[0]
y_pred_rf = results_ml['Random Forest']['y_pred']
ax.scatter(y_test, y_pred_rf, alpha=0.6, color='#2E75B6', s=60)
lim = max(y_test.max(), y_pred_rf.max())
ax.plot([0,lim],[0,lim],'r--',linewidth=2,label='Mükemmel Tahmin')
ax.set_xlabel('Gerçek Maliyet')
ax.set_ylabel('Tahmin')
ax.set_title(f'Tahmin vs Gerçek\nR²={results_ml["Random Forest"]["r2"]:.3f}', fontweight='bold')
ax.legend()

ax = axes[1]
colors_fi = ['#E24B4A' if v > feat_imp.mean() else '#2E75B6' for v in feat_imp.values]
ax.barh(range(len(feat_imp)), feat_imp.values, color=colors_fi)
ax.set_yticks(range(len(feat_imp)))
ax.set_yticklabels(feat_imp.index, fontsize=9)
ax.set_title('En Önemli 8 Özellik', fontweight='bold')
ax.set_xlabel('Önem Skoru')

plt.tight_layout()
plt.show()

# Özet Rapor
print("=" * 55)
print("TEDARİK ZİNCİRİ ANALİZİ — ÖZET RAPOR")
print("=" * 55)

print(f"\nVERİ SETİ:")
print(f"  {len(df)} SKU, {df['Supplier name'].nunique()} tedarikçi, {df['Location'].nunique()} lokasyon")
print(f"  Ort. temin süresi : {df['Lead times'].mean():.1f} gün")
print(f"  Ort. hata oranı   : {df['Defect rates'].mean():.2f}%")
print(f"  Ort. stok seviyesi: {df['Stock levels'].mean():.0f} adet")

print(f"\nBULLWHIP ETKİSİ:")
print(f"  Perakendeci : {bwe_retailer:.2f}x")
print(f"  Toptancı    : {bwe_wholesaler:.2f}x")
print(f"  Üretici     : {bwe_manufacturer:.2f}x")
print(f"  Tedarikçi   : {bwe_supplier:.2f}x  ← Kritik!")

print(f"\nML MODELİ (Maliyet Tahmini):")
print(f"  En iyi model : Random Forest")
print(f"  R²           : {results_ml['Random Forest']['r2']:.3f}")
print(f"  MAE          : {results_ml['Random Forest']['mae']:.1f} ₺")

print(f"\nTEDARİKÇİ PERFORMANS:")
print(f"  En iyi tedarikçi  : {supplier_perf['Performans_Skoru'].idxmax()} (Skor: {supplier_perf['Performans_Skoru'].max()})")
print(f"  En düşük hata     : {supplier_perf['Ort_Hata_Orani'].idxmin()}")
print(f"  En hızlı temin    : {supplier_perf['Ort_Temin_Suresi'].idxmin()}")

print(f"\nKAİZEN ÖNERİLERİ:")
print(f"  1. Tedarikçilerle bilgi paylaşımı → Bullwhip azaltır")
print(f"  2. {supplier_perf['Performans_Skoru'].idxmax()} ile ortaklığı güçlendir")
print(f"  3. {supplier_perf['Ort_Hata_Orani'].idxmax()} için kalite programı başlat")
print(f"  4. Stok devir hızı düşük ürünler için EOQ uygula")
print(f"  5. ABC A sınıfı ürünler için özel takip sistemi kur")
print("\n" + "=" * 55)
print("Proje tamamlandi!")